### ISSUE TITLE
ConditionalOnBean does not work in some situations

### ISSUE THREAD

**Issue by jebl01** [snicoll/spring-boot-master-auto-configuration#1]
There seems to be an issue with ConditionalOnBean (maybe for other conditions as well?) if the configuration shares the root package with the consumer.

This bit me hard, and I think it's at least worth mentioning in the docs and in this demo. I have set up a repo showing this here: https://github.com/jebl01/spring-auto-config-lab

**Comment by snicoll** [comment]
I wasn't watching the repo so sorry for not replying here. Hopefully you got it in the meantime. auto-configurations should be defined in their own package. We've fixed this in case you forget by disabling scanning of auto-configurations.
