### ISSUE TITLE
can this be updated for spring 3?

### ISSUE THREAD

**Issue by andresmonc** [snicoll/spring-boot-master-auto-configuration#11]

**Comment by snicoll** [comment]
I am afraid not. That's a rather old talk that was relying on the fact we didn't have auto-configuration for a certain component (HornetQ). We did in more recent of spring boot so we'd have to rewrite the whole thing to use something else. If you're having a specific issue, please consider asking on StackOverflow or Gitter.

**Comment by snicoll** [comment]
@andresmonc the update of this talk is https://github.com/snicoll/hello-service-auto-configuration. If you're interested, I can upgrade that to SB3.
