### ISSUE TITLE
Video mentioned in README no longer available?

### ISSUE THREAD

**Issue by rssole** [snicoll/spring-boot-master-auto-configuration#3]
Is it moved or removed? If former, could you please update link accordingly?

This repo is mentioned within Boot documentation so perhaps people'd like to take a look.

Cheers,

**Comment by seguri** [comment]
_I think_ the original video is from [SpringIO 15](https://ordina-jworks.github.io/spring/2015/05/08/SpringIO15-Autoconfig.html). But here's a similar one from SpringIO 17: [It's a kind of magic: under the covers of Spring Boot](https://www.youtube.com/watch?v=N39hpGAT43s).

**Comment by snicoll** [comment]
Unfortunately, they did remove the video, I have no idea why. I couldn't find a recording from Spring IO 2015 and I don't remember if it was the same thing. I have removed the link to the video.
